export const DECREASE_COUNT = 'DECREASE_COUNT';
export const START_GAME = 'START_GAME';
export const RESET_GAME = 'RESET_GAME';
export const USER_SELECTION = 'USER_SELECTION';
export const CPU_SELECTION = 'CPU_SELECTION';
export const FINISH_ROUND = 'FINISH_ROUND';
